name: Multi-Stage (Jobs) GH Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux_build:
    runs-on: ubuntu-latest
    env:
      file_path: build/linux-hello
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for linux
        env:
          GOOS: linux
        working-directory: src-go
        run: |
          go build -o $file_path
      - name: upload archive
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: src-go/${{ env.file_path }}
  
  windows_build:
    runs-on: ubuntu-latest
    env:
      file_path: build/windows-hello.exe
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for windows
        env:
          GOOS: windows
        working-directory: src-go
        run: |
          go build -o $file_path
      - name: upload archive
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: src-go/${{ env.file_path }}
                  
  macos_build:
    runs-on: ubuntu-latest
    env:
      file_path: build/macos-hello
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for macos
        env:
          GOOS: darwin
        working-directory: src-go
        run: |
          go build -o $file_path
      - name: upload archive
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: src-go/${{ env.file_path }}
  
  archive_results:
    runs-on: ubuntu-latest
    needs: 
      - macos_build
      - linux_build
      - windows_build
    steps:
      - name: download archives
        uses: actions/download-artifact@v4
      - name: list artifacts
        run: |
          ls -al
      - name: upload artifact together
        uses: actions/upload-artifact@v4
        with: 
          name: combined
          path: .
