on:
  release:
    types:
      - released

name: Release Marked as stable

jobs:
  tag-update:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get Target Commit SHA
        id: get_sha
        run: echo "target_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Echo hello world
        run: |
          echo "Hello, world! This is a release marked as stable."
