name: Play with Application

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Python Virtual Environment
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    
    - name: Build the application
      shell: bash
      run: |
        source .venv/bin/activate
        pyinstaller src/main.py --onefile
    
    - name: Archive the build
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: dist/
