name: Play with Application

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Python Virtual Environment
      shell: bash
      env:
        ACTIVATE_SCRIPT: if {{ runner.os }} == 'Windows' {echo ".venv/Scripts/activate" } else { echo "source .venv/bin/activate" }
      run: |
        python3 -m venv .venv
        ${{ env.ACTIVATE_SCRIPT }}
        pip install -r requirements.txt
    
    - name: Build the application
      shell: bash
      env:
        ACTIVATE_SCRIPT: if {{ runner.os }} == 'Windows' {echo ".venv/Scripts/activate" } else { echo "source .venv/bin/activate" }
      run: |
        ${{ env.ACTIVATE_SCRIPT }}
        pyinstaller src/main.py --onefile
    
    - name: Archive the build
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: dist/
