name: Multi-Stage (Jobs) GH Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for linux
        env:
          GOOS: linux
        working-directory: src-go
        run: |
          go build -o build/linux-hello
  
  windows_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for windows
        env:
          GOOS: windows
        working-directory: src-go
        run: |
          go build -o build/windows-hello.exe
                  
  macos_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build for macos
        env:
          GOOS: darwin
        working-directory: src-go
        run: |
          go build -o build/macos-hello
  
  archive_results:
    runs-on: ubuntu-latest
    steps:
      - name: archive-build-files
        run: ls -al -R
