name: Outputs example

on:
  workflow_dispatch:

jobs:
  create_output:
    runs-on: ubuntu-latest
    steps:
      - name: Create an output
        id: creator
        run: |
          echo "NAME=Ganesh" >> $GITHUB_OUTPUT
      - name: User
        id: user
        env:
          VALUE: ${{ steps.creator.outputs.NAME }}
        run: |
          echo "value of output is $VALUE" 
  # subscriber:
  #   needs: 
  #     - create_output
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: read output
  #       env:
  #         NAME: ${{ needs.create_output.outputs.NAME }}
  #       run: |
  #         echo "Output from previous step is: $NAME" 
