on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

name: Test Zx By Google

jobs:
  first-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zx
        run: |
          npm install zx

      - name: Run zx script
        run: |
          chmod +x zx-scripts/getting-started.mjs
          ./zx-scripts/getting-started.mjs
