on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

name: Test Zx By Google

jobs:
  first-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zx
        working-directory: zx-scripts
        run: |
          npm install

      - name: Run zx script
        working-directory: zx-scripts
        run: |
          npm run test
